name: flutter_frappe_chat
description: A customizable Flutter package for Frappe Chat integration with WebSocket and API handling.
version: 0.1.2
homepage: https://github.com/handoud/flutter_frappe_chat

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Networking
  socket_io_client: ^3.0.0
  http: ^1.1.0
  dio: ^5.3.3 # Often better for file uploads
  
  # File & Media
  file_picker: ^10.3.8
  image_picker: ^1.0.4
  mime: ^1.0.4
  path: ^1.8.3
  
  # Audio
  flutter_sound: ^9.2.13
  # permission_handler: ^11.3.1 # User requested permissions
  permission_handler: ^12.0.1 # Using a stable version compatible with recent flutter

  # UI
  intl: ^0.20.2
  cached_network_image: ^3.3.0
  flutter_pdfview: ^1.3.2 # For inline PDF viewing
  url_launcher: ^6.1.14

  # State Management
  provider: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
